DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS session CASCADE;
DROP TABLE IF EXISTS server CASCADE;
DROP TABLE IF EXISTS server_profile CASCADE;
DROP TABLE IF EXISTS channel CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS permission CASCADE;
DROP TABLE IF EXISTS sticker_pack CASCADE;
DROP TABLE IF EXISTS sticker CASCADE;
DROP TABLE IF EXISTS message CASCADE;


