CREATE TABLE IF NOT EXISTS session(
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT UNIQUE NOT NULL,
    token TEXT UNIQUE NOT NULL,
    expired_at TIMESTAMP NOT NULL
--     FOREIGN KEY user_id REFERENCES user(id)
)


CREATE TABLE IF NOT EXISTS 